require: ['rubocop-rspec', 'rubocop-performance']

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  CacheRootDirectory: ./tmp
  Exclude:
    - certs/*
  NewCops: enable

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Performance/StringReplacement:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false
RSpec/ExampleLength:
  Max: 25
RSpec/MultipleExpectations:
  Max: 10
RSpec/NestedGroups:
  Max: 4
RSpec/LetSetup:
  Enabled: false
# @todo switch from mocha mocking to rspec mocks & use doubles
RSpec/AnyInstance:
  Enabled: false

Style/GuardClause:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
